// script.js — client-side logic for nextycod demo
// NOTE: AI credit has been customized to show "Generated by nexty"
document.addEventListener('DOMContentLoaded',()=>{
  const loginForm = document.getElementById('loginForm');
  const loginMsg = document.getElementById('loginMsg');
  const toolsCard = document.getElementById('toolsCard');
  const who = document.getElementById('who');

  // Demo credentials
  const DEMO_USER = 'nexty';
  const DEMO_PASS = 'ofcnexty';

  loginForm.addEventListener('submit', ev=>{
    ev.preventDefault();
    const u = document.getElementById('username').value.trim();
    const p = document.getElementById('password').value.trim();

    if(u===DEMO_USER && p===DEMO_PASS){
      // success
      loginMsg.style.display='none';
      who.textContent = u;
      showTools();
    } else {
      loginMsg.style.display='block';
      loginMsg.textContent = 'Invalid credentials — try nexty / ofcnexty';
    }
  });

  function showTools(){
    document.getElementById('loginForm').style.display='none';
    toolsCard.style.display='block';
  }

  // AI generator
  const genBtn = document.getElementById('genBtn');
  const aiPrompt = document.getElementById('aiPrompt');
  const aiAspect = document.getElementById('aiAspect');
  const aiStatus = document.getElementById('aiStatus');
  const aiPreview = document.getElementById('aiPreview');

  genBtn.addEventListener('click', async ()=>{
    const prompt = aiPrompt.value.trim();
    const aspect = aiAspect.value;
    if(!prompt){ aiStatus.textContent='Please type a prompt.'; return; }
    aiStatus.textContent = 'Requesting image...';
    aiPreview.innerHTML = '';

    // Use the public FAM OFC API (GET example) — no API key required
    // We encode prompt and aspect ratio into query string
    const url = `https://famofc.site/api/generate.php?prompt=${encodeURIComponent(prompt)}&aspectRatio=${encodeURIComponent(aspect)}`;

    try{
      const res = await fetch(url);
      if(!res.ok) throw new Error('Network error');
      const data = await res.json();
      if(!data.success || !Array.isArray(data.images) || data.images.length===0){
        aiStatus.textContent = 'No image returned.';
        return;
      }
      // OVERRIDE credit to show the user's credit name: "nexty"
      aiStatus.textContent = 'Generated by nexty';
      // show first image
      const img = document.createElement('img');
      img.src = data.images[0].image_url;
      img.alt = prompt;
      aiPreview.appendChild(img);

    }catch(err){
      console.error(err);
      aiStatus.textContent = 'Error: '+err.message;
    }
  });

  // SIM lookup (demo)
  const simBtn = document.getElementById('simBtn');
  const simInput = document.getElementById('simInput');
  const simResult = document.getElementById('simResult');

  simBtn.addEventListener('click', async ()=>{
    const q = simInput.value.trim();
    if(!q){ simResult.textContent='Enter phone number.'; return; }
    simResult.textContent = 'Looking up...';
    try{
      // call our demo server endpoint — adjust path if needed on your server
      const res = await fetch(`/api/simlookup?phone=${encodeURIComponent(q)}`);
      if(!res.ok) throw new Error('Lookup failed');
      const data = await res.json();
      simResult.textContent = JSON.stringify(data, null, 2);
    }catch(err){
      simResult.textContent = 'Error: '+err.message;
    }
  });

});
